Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members!

In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT Facility, sum(cost) AS Revenue
FROM (SELECT Facilities.name AS Facility,
	CASE WHEN Bookings.memid = 0 THEN guestcost*slots
	ELSE membercost*slots END AS cost
	FROM Bookings
	INNER JOIN Facilities ON Bookings.facid = Facilities.facid
	INNER JOIN Members ON Bookings.memid = Members.memid) AS subquerry
GROUP BY Facility
HAVING Revenue < 1000
ORDER BY Revenue;"""
    cur.execute(query1)
    rows = cur.fetchall()
     
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT surname ||',' || firstname AS Full_name, subquerry.full_name AS Recommended_by
FROM Members
INNER JOIN (SELECT DISTINCT memid AS ID, surname ||',' || firstname AS Full_name FROM Members) AS subquerry
ON Members.recommendedby= subquerry.ID
WHERE surname NOT LIKE 'GUEST' AND recommendedby >=1
        """
    cur.execute(query1)
    rows = cur.fetchall()
     
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Joplette,Janice', 'Smith,Darren')
('Butters,Gerald', 'Smith,Darren')
('Dare,Nancy', 'Joplette,Janice')
('Boothe,Tim', 'Rownam,Tim')
('Stibbons,Ponder', 'Tracy,Burton')
('Owen,Charles', 'Smith,Darren')
('Jones,David', 'Joplette,Janice')
('Baker,Anne', 'Stibbons,Ponder')
('Smith,Jack', 'Smith,Darren')
('Bader,Florence', 'Stibbons,Ponder')
('Baker,Timothy', 'Farrell,Jemima')
('Pinker,David', 'Farrell,Jemima')
('Genting,Matthew', 'Butters,Gerald')
('Mackenzie,Anna', 'Smith,Darren')
('Coplin,Joan', 'Baker,Timothy')
('Sarwin,Ramnaresh', 'Bader,Florence')
('Jones,Douglas', 'Jones,David')
('Rumney,Henrietta', 'Genting,Matthew')
('Worthington-Smyth,Henry', 'Smith,Tracy')
('Purview,Millicent', 'Smith,Tracy')
('Hunt,John', 'Purview,Millicent')
('Crumpet,Erica', 'Smith,Tracy')

Q12: Find the facilities with their usage by member, but not guests

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT Facilities.name, count(Facilities.name) as Bookings
FROM Bookings
INNER JOIN Members
ON Bookings.memid = Members.memid
INNER JOIN Facilities
ON Bookings.facid = Facilities.facid
WHERE surname NOT LIKE 'GUEST'
GROUP BY name;
        """
    cur.execute(query1)
    rows = cur.fetchall()
     
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 344)
('Massage Room 1', 421)
('Massage Room 2', 27)
('Pool Table', 783)
('Snooker Table', 421)
('Squash Court', 195)
('Table Tennis', 385)
('Tennis Court 1', 308)
('Tennis Court 2', 276)

Q13: Find the facilities usage by month, but not guests

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT
sum(case when strftime('%m',date(starttime)) = '01' then 1 else 0 end) as 'Jan',
sum(case when strftime('%m',date(starttime)) = '02' then 1 else 0 end) as 'Feb',
sum(case when strftime('%m',date(starttime)) = '03' then 1 else 0 end) as 'Mar',
sum(case when strftime('%m',date(starttime)) = '04' then 1 else 0 end) as 'Apr',
sum(case when strftime('%m',date(starttime)) = '05' then 1 else 0 end) as 'May',
sum(case when strftime('%m',date(starttime)) = '06' then 1 else 0 end) as 'Jun',
sum(case when strftime('%m',date(starttime)) = '07' then 1 else 0 end) as 'Jul',
sum(case when strftime('%m',date(starttime)) = '08' then 1 else 0 end) as 'Aug',
sum(case when strftime('%m',date(starttime)) = '09' then 1 else 0 end) as 'Sep',
sum(case when strftime('%m',date(starttime)) = '10' then 1 else 0 end) as 'Oct',
sum(case when strftime('%m',date(starttime)) = '11' then 1 else 0 end) as 'Nov',
sum(case when strftime('%m',date(starttime)) = '12' then 1 else 0 end) as 'Dec'
FROM Bookings
INNER JOIN Members
ON Bookings.memid = Members.memid
INNER JOIN Facilities
ON Bookings.facid = Facilities.facid
WHERE surname NOT LIKE 'GUEST';

        """
    cur.execute(query1)
    rows = cur.fetchall()
     
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 0, 0, 0, 0, 0, 480, 1168, 1512, 0, 0, 0)